steps:
  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "deploy"
    entrypoint: /bin/sh
    args:
      - "-c"
      - firebase deploy --only hosting --token $_FIREBASE_TOKEN --project $PROJECT_ID

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "ui tests (test environment)"
    entrypoint: /bin/sh
    args:
      - "-c"
      - export BASE_URL=$_BASE_URL && yarn ui-test
  # TODO: deploy to live here
  # TODO: re-run UI tests here
