steps:
  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "dependencies"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn install

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "format check"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn prettier --check src/**/*.js

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "unit test"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn test

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "build"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn build

  # TODO: deploy to live here
  # TODO: re-run UI tests here

  substitutions:
    _CONFIG: test