steps:
  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "version"
    entrypoint: /bin/sh
    args:
      - "-c"
      - echo VUE_APP_VERSION=$SHORT_SHA >> file && echo VUE_APP_LAST_UPDATED=$(date --iso-8601=minutes) >> file

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "deploy"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn install && yarn build --mode $_CONFIG && firebase deploy --only hosting --token $_FIREBASE_TOKEN --project $PROJECT_ID

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "test"
    entrypoint: /bin/sh
    args:
      - "-c"
      - BASE_URL=$_BASE_URL && yarn test

substitutions:
  _CONFIG: test
