steps:
  - name: "gcr.io/tired-lemur/slackbot"
    args:
      [
        "--build",
        "$BUILD_ID",
        "--webhook",
        $_SLACK_WEBHOOK,
        "--name",
        "$_BUILD_NAME",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config=cloudbuild.build.yaml",
        "--substitutions=_CONFIG=$_CONFIG",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["builds", "submit", "--config=cloudbuild.deploy.yaml"]

  # TODO: deploy to live here
  # TODO: re-run UI tests here

substitutions:
  _CONFIG: test
