steps:
  - name: "gcr.io/tired-lemur/slackbot"
    args:
      [
        "--build",
        "$BUILD_ID",
        "--webhook",
        $_SLACK_WEBHOOK,
        "--name",
        "$_BUILD_NAME",
      ]

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "version"
    entrypoint: /bin/sh
    args:
      - "-c"
      - echo VUE_APP_VERSION=$SHORT_SHA >> file && echo VUE_APP_LAST_UPDATED=$(date --iso-8601=minutes) >> .env.local

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "dependencies"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn install

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "format check"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn prettier --check src/**/*.js

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "unit test"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn test

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "build"
    entrypoint: /bin/sh
    args:
      - "-c"
      - yarn build --mode $_CONFIG

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "deploy"
    entrypoint: /bin/sh
    args:
      - "-c"
      - firebase deploy --only hosting --token $_FIREBASE_TOKEN --project $PROJECT_ID

  - name: "gcr.io/tired-lemur/frontend-devcontainer:latest"
    id: "ui tests (test environment)"
    entrypoint: /bin/sh
    args:
      - "-c"
      - export BASE_URL=$_BASE_URL && yarn ui-test

  # TODO: deploy to live here
  # TODO: re-run UI tests here

substitutions:
  _CONFIG: test
