steps:
  - name: "gcr.io/tired-lemur/slackbot"
    args:
      [
        "--build",
        "$BUILD_ID",
        "--webhook",
        $_SLACK_WEBHOOK,
        "--name",
        "$_BUILD_NAME",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config=cloudbuild.build.yaml",
        "--substitutions=_CONFIG=$_CONFIG",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--config=cloudbuild.deploy.yaml",
        "--substitutions=_FIREBASE_TOKEN=$_FIREBASE_TOKEN,_BASE_URL=$_BASE_URL",
      ]
  # TODO: deploy to live here
  # TODO: re-run UI tests here
